version: "3"

services:
  mysql:
    image: mysql:5.6
    container_name: api-mysql
    working_dir: /application
  ports:
      - "3103:3306" 
  environment:
      - MYSQL_ROOT_PASSWORD=er0s1ntl
      - MYSQL_DATABASE=go_high
      - MYSQL_USER=root
      - MYSQL_PASSWORD=er0s1ntl
volumes:
  mysql