version: '3.3'
services:
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'er0s1ntl'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3103:3306'
    expose:
      # Opens port 3306 on the container
      - '3103'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  web:
      build: .
      depends_on:
        - db
      volumes:
        - ./src/:/src/
      ports:
        - "3000:3000"
      

# Names our volume
volumes:
  my-db:
